// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pop_stream.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pop_stream::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pop_stream::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> pop_stream::ap_ST_fsm_state1 = "1";
const sc_lv<32> pop_stream::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool pop_stream::ap_const_boolean_1 = true;

pop_stream::pop_stream(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );
    sensitive << ( ret_fu_80_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_e_data_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );

    SC_METHOD(thread_e_data_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_dest_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_dest_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_id_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_id_V_empty_n );

    SC_METHOD(thread_e_id_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_keep_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_keep_V_empty_n );

    SC_METHOD(thread_e_keep_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_last_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_last_V_empty_n );

    SC_METHOD(thread_e_last_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_strb_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_strb_V_empty_n );

    SC_METHOD(thread_e_strb_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_e_user_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_user_V_empty_n );

    SC_METHOD(thread_e_user_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    SC_METHOD(thread_ret_fu_80_p1);
    sensitive << ( e_data_V_dout );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( e_data_V_empty_n );
    sensitive << ( e_keep_V_empty_n );
    sensitive << ( e_strb_V_empty_n );
    sensitive << ( e_user_V_empty_n );
    sensitive << ( e_last_V_empty_n );
    sensitive << ( e_id_V_empty_n );
    sensitive << ( e_dest_V_empty_n );

    ap_CS_fsm = "1";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pop_stream_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, e_data_V_dout, "(port)e_data_V_dout");
    sc_trace(mVcdFile, e_data_V_empty_n, "(port)e_data_V_empty_n");
    sc_trace(mVcdFile, e_data_V_read, "(port)e_data_V_read");
    sc_trace(mVcdFile, e_keep_V_dout, "(port)e_keep_V_dout");
    sc_trace(mVcdFile, e_keep_V_empty_n, "(port)e_keep_V_empty_n");
    sc_trace(mVcdFile, e_keep_V_read, "(port)e_keep_V_read");
    sc_trace(mVcdFile, e_strb_V_dout, "(port)e_strb_V_dout");
    sc_trace(mVcdFile, e_strb_V_empty_n, "(port)e_strb_V_empty_n");
    sc_trace(mVcdFile, e_strb_V_read, "(port)e_strb_V_read");
    sc_trace(mVcdFile, e_user_V_dout, "(port)e_user_V_dout");
    sc_trace(mVcdFile, e_user_V_empty_n, "(port)e_user_V_empty_n");
    sc_trace(mVcdFile, e_user_V_read, "(port)e_user_V_read");
    sc_trace(mVcdFile, e_last_V_dout, "(port)e_last_V_dout");
    sc_trace(mVcdFile, e_last_V_empty_n, "(port)e_last_V_empty_n");
    sc_trace(mVcdFile, e_last_V_read, "(port)e_last_V_read");
    sc_trace(mVcdFile, e_id_V_dout, "(port)e_id_V_dout");
    sc_trace(mVcdFile, e_id_V_empty_n, "(port)e_id_V_empty_n");
    sc_trace(mVcdFile, e_id_V_read, "(port)e_id_V_read");
    sc_trace(mVcdFile, e_dest_V_dout, "(port)e_dest_V_dout");
    sc_trace(mVcdFile, e_dest_V_empty_n, "(port)e_dest_V_empty_n");
    sc_trace(mVcdFile, e_dest_V_read, "(port)e_dest_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, e_data_V_blk_n, "(port)e_data_V_blk_n");
    sc_trace(mVcdFile, e_keep_V_blk_n, "(port)e_keep_V_blk_n");
    sc_trace(mVcdFile, e_strb_V_blk_n, "(port)e_strb_V_blk_n");
    sc_trace(mVcdFile, e_user_V_blk_n, "(port)e_user_V_blk_n");
    sc_trace(mVcdFile, e_last_V_blk_n, "(port)e_last_V_blk_n");
    sc_trace(mVcdFile, e_id_V_blk_n, "(port)e_id_V_blk_n");
    sc_trace(mVcdFile, e_dest_V_blk_n, "(port)e_dest_V_blk_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ret_fu_80_p1, "ret_fu_80_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pop_stream::~pop_stream() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void pop_stream::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
            ap_return_preg = ret_fu_80_p1.read();
        }
    }
}

void pop_stream::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pop_stream::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read()));
}

void pop_stream::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pop_stream::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pop_stream::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pop_stream::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        ap_return = ret_fu_80_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void pop_stream::thread_e_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_data_V_blk_n = e_data_V_empty_n.read();
    } else {
        e_data_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_data_V_read = ap_const_logic_1;
    } else {
        e_data_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_dest_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_dest_V_blk_n = e_dest_V_empty_n.read();
    } else {
        e_dest_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_dest_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_dest_V_read = ap_const_logic_1;
    } else {
        e_dest_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_id_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_id_V_blk_n = e_id_V_empty_n.read();
    } else {
        e_id_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_id_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_id_V_read = ap_const_logic_1;
    } else {
        e_id_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_keep_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_keep_V_blk_n = e_keep_V_empty_n.read();
    } else {
        e_keep_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_keep_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_keep_V_read = ap_const_logic_1;
    } else {
        e_keep_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_last_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_last_V_blk_n = e_last_V_empty_n.read();
    } else {
        e_last_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_last_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_last_V_read = ap_const_logic_1;
    } else {
        e_last_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_strb_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_strb_V_blk_n = e_strb_V_empty_n.read();
    } else {
        e_strb_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_strb_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_strb_V_read = ap_const_logic_1;
    } else {
        e_strb_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_e_user_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_user_V_blk_n = e_user_V_empty_n.read();
    } else {
        e_user_V_blk_n = ap_const_logic_1;
    }
}

void pop_stream::thread_e_user_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_strb_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_keep_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_user_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_last_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_id_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, e_dest_V_empty_n.read())))) {
        e_user_V_read = ap_const_logic_1;
    } else {
        e_user_V_read = ap_const_logic_0;
    }
}

void pop_stream::thread_ret_fu_80_p1() {
    ret_fu_80_p1 = e_data_V_dout.read();
}

void pop_stream::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

