// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "push_stream.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic push_stream::ap_const_logic_1 = sc_dt::Log_1;
const bool push_stream::ap_const_boolean_1 = true;
const sc_logic push_stream::ap_const_logic_0 = sc_dt::Log_0;

push_stream::push_stream(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( v_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "push_stream_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, v_read, "(port)v_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif

    }
}

push_stream::~push_stream() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void push_stream::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void push_stream::thread_ap_return() {
    ap_return = v_read.read();
}

}

