// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mult_accel_core_call,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007sclg225-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.770500,HLS_SYN_LAT=1571,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=218,HLS_VERSION=2018_3}" *)

module mult_accel_core_call (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_data_V_dout,
        in_stream_data_V_empty_n,
        in_stream_data_V_read,
        in_stream_keep_V_dout,
        in_stream_keep_V_empty_n,
        in_stream_keep_V_read,
        in_stream_strb_V_dout,
        in_stream_strb_V_empty_n,
        in_stream_strb_V_read,
        in_stream_user_V_dout,
        in_stream_user_V_empty_n,
        in_stream_user_V_read,
        in_stream_last_V_dout,
        in_stream_last_V_empty_n,
        in_stream_last_V_read,
        in_stream_id_V_dout,
        in_stream_id_V_empty_n,
        in_stream_id_V_read,
        in_stream_dest_V_dout,
        in_stream_dest_V_empty_n,
        in_stream_dest_V_read,
        out_stream_data_V_dout,
        out_stream_data_V_empty_n,
        out_stream_data_V_read,
        out_stream_keep_V_din,
        out_stream_keep_V_full_n,
        out_stream_keep_V_write,
        out_stream_strb_V_din,
        out_stream_strb_V_full_n,
        out_stream_strb_V_write,
        out_stream_user_V_din,
        out_stream_user_V_full_n,
        out_stream_user_V_write,
        out_stream_last_V_din,
        out_stream_last_V_full_n,
        out_stream_last_V_write,
        out_stream_id_V_din,
        out_stream_id_V_full_n,
        out_stream_id_V_write,
        out_stream_dest_V_din,
        out_stream_dest_V_full_n,
        out_stream_dest_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_stream_data_V_dout;
input   in_stream_data_V_empty_n;
output   in_stream_data_V_read;
input  [3:0] in_stream_keep_V_dout;
input   in_stream_keep_V_empty_n;
output   in_stream_keep_V_read;
input  [3:0] in_stream_strb_V_dout;
input   in_stream_strb_V_empty_n;
output   in_stream_strb_V_read;
input  [3:0] in_stream_user_V_dout;
input   in_stream_user_V_empty_n;
output   in_stream_user_V_read;
input  [0:0] in_stream_last_V_dout;
input   in_stream_last_V_empty_n;
output   in_stream_last_V_read;
input  [4:0] in_stream_id_V_dout;
input   in_stream_id_V_empty_n;
output   in_stream_id_V_read;
input  [4:0] in_stream_dest_V_dout;
input   in_stream_dest_V_empty_n;
output   in_stream_dest_V_read;
input  [31:0] out_stream_data_V_dout;
input   out_stream_data_V_empty_n;
output   out_stream_data_V_read;
output  [3:0] out_stream_keep_V_din;
input   out_stream_keep_V_full_n;
output   out_stream_keep_V_write;
output  [3:0] out_stream_strb_V_din;
input   out_stream_strb_V_full_n;
output   out_stream_strb_V_write;
output  [3:0] out_stream_user_V_din;
input   out_stream_user_V_full_n;
output   out_stream_user_V_write;
output  [0:0] out_stream_last_V_din;
input   out_stream_last_V_full_n;
output   out_stream_last_V_write;
output  [4:0] out_stream_id_V_din;
input   out_stream_id_V_full_n;
output   out_stream_id_V_write;
output  [4:0] out_stream_dest_V_din;
input   out_stream_dest_V_full_n;
output   out_stream_dest_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_stream_keep_V_write;
reg out_stream_strb_V_write;
reg out_stream_user_V_write;
reg out_stream_last_V_write;
reg out_stream_id_V_write;
reg out_stream_dest_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_mult_accel_core_fu_58_ap_start;
wire    grp_mult_accel_core_fu_58_ap_done;
wire    grp_mult_accel_core_fu_58_ap_idle;
wire    grp_mult_accel_core_fu_58_ap_ready;
wire   [3:0] grp_mult_accel_core_fu_58_out_stream_keep_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_keep_V_write;
wire   [3:0] grp_mult_accel_core_fu_58_out_stream_strb_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_strb_V_write;
wire   [3:0] grp_mult_accel_core_fu_58_out_stream_user_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_user_V_write;
wire   [0:0] grp_mult_accel_core_fu_58_out_stream_last_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_last_V_write;
wire   [4:0] grp_mult_accel_core_fu_58_out_stream_id_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_id_V_write;
wire   [4:0] grp_mult_accel_core_fu_58_out_stream_dest_V_din;
wire    grp_mult_accel_core_fu_58_out_stream_dest_V_write;
reg    grp_mult_accel_core_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_mult_accel_core_fu_58_ap_start_reg = 1'b0;
end

mult_accel_core grp_mult_accel_core_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mult_accel_core_fu_58_ap_start),
    .ap_done(grp_mult_accel_core_fu_58_ap_done),
    .ap_idle(grp_mult_accel_core_fu_58_ap_idle),
    .ap_ready(grp_mult_accel_core_fu_58_ap_ready),
    .out_stream_keep_V_din(grp_mult_accel_core_fu_58_out_stream_keep_V_din),
    .out_stream_keep_V_full_n(out_stream_keep_V_full_n),
    .out_stream_keep_V_write(grp_mult_accel_core_fu_58_out_stream_keep_V_write),
    .out_stream_strb_V_din(grp_mult_accel_core_fu_58_out_stream_strb_V_din),
    .out_stream_strb_V_full_n(out_stream_strb_V_full_n),
    .out_stream_strb_V_write(grp_mult_accel_core_fu_58_out_stream_strb_V_write),
    .out_stream_user_V_din(grp_mult_accel_core_fu_58_out_stream_user_V_din),
    .out_stream_user_V_full_n(out_stream_user_V_full_n),
    .out_stream_user_V_write(grp_mult_accel_core_fu_58_out_stream_user_V_write),
    .out_stream_last_V_din(grp_mult_accel_core_fu_58_out_stream_last_V_din),
    .out_stream_last_V_full_n(out_stream_last_V_full_n),
    .out_stream_last_V_write(grp_mult_accel_core_fu_58_out_stream_last_V_write),
    .out_stream_id_V_din(grp_mult_accel_core_fu_58_out_stream_id_V_din),
    .out_stream_id_V_full_n(out_stream_id_V_full_n),
    .out_stream_id_V_write(grp_mult_accel_core_fu_58_out_stream_id_V_write),
    .out_stream_dest_V_din(grp_mult_accel_core_fu_58_out_stream_dest_V_din),
    .out_stream_dest_V_full_n(out_stream_dest_V_full_n),
    .out_stream_dest_V_write(grp_mult_accel_core_fu_58_out_stream_dest_V_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mult_accel_core_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_mult_accel_core_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_mult_accel_core_fu_58_ap_ready == 1'b1)) begin
            grp_mult_accel_core_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((grp_mult_accel_core_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mult_accel_core_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_dest_V_write = grp_mult_accel_core_fu_58_out_stream_dest_V_write;
    end else begin
        out_stream_dest_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_id_V_write = grp_mult_accel_core_fu_58_out_stream_id_V_write;
    end else begin
        out_stream_id_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_keep_V_write = grp_mult_accel_core_fu_58_out_stream_keep_V_write;
    end else begin
        out_stream_keep_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_last_V_write = grp_mult_accel_core_fu_58_out_stream_last_V_write;
    end else begin
        out_stream_last_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_strb_V_write = grp_mult_accel_core_fu_58_out_stream_strb_V_write;
    end else begin
        out_stream_strb_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_user_V_write = grp_mult_accel_core_fu_58_out_stream_user_V_write;
    end else begin
        out_stream_user_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_mult_accel_core_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_mult_accel_core_fu_58_ap_start = grp_mult_accel_core_fu_58_ap_start_reg;

assign in_stream_data_V_read = 1'b0;

assign in_stream_dest_V_read = 1'b0;

assign in_stream_id_V_read = 1'b0;

assign in_stream_keep_V_read = 1'b0;

assign in_stream_last_V_read = 1'b0;

assign in_stream_strb_V_read = 1'b0;

assign in_stream_user_V_read = 1'b0;

assign out_stream_data_V_read = 1'b0;

assign out_stream_dest_V_din = grp_mult_accel_core_fu_58_out_stream_dest_V_din;

assign out_stream_id_V_din = grp_mult_accel_core_fu_58_out_stream_id_V_din;

assign out_stream_keep_V_din = grp_mult_accel_core_fu_58_out_stream_keep_V_din;

assign out_stream_last_V_din = grp_mult_accel_core_fu_58_out_stream_last_V_din;

assign out_stream_strb_V_din = grp_mult_accel_core_fu_58_out_stream_strb_V_din;

assign out_stream_user_V_din = grp_mult_accel_core_fu_58_out_stream_user_V_din;

endmodule //mult_accel_core_call
